apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobilenet-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobilenet
  template:
    metadata:
      labels:
        app: mobilenet
    spec:
      containers:
        - name: mobilenet-container
          image: gender-api
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mobilenet-service
spec:
  type: NodePort
  selector:
    app: mobilenet
  ports:
    - port: 5000
      targetPort: 5000